In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Credit Card Default II (balance).csv")

In [4]:
print(df)

            income        age          loan  default
0     66155.925100  59.017015   8106.532131        0
1     34415.153970  48.117153   6564.745018        0
2     57317.170060  63.108049   8020.953296        0
3     42709.534200  45.751972   6103.642260        0
4     66952.688850  18.584336   8770.099235        1
...            ...        ...           ...      ...
3423  60903.191726  21.933924  10367.081892        1
3424  62235.644695  25.033016   8083.900063        1
3425  25597.850590  26.350344   3810.110335        1
3426  48164.194974  23.141976   6529.652892        1
3427  33055.808635  26.289612   5351.851138        1

[3428 rows x 4 columns]


In [6]:
print(df.isnull().sum().sort_values()) #no null values

income     0
age        0
loan       0
default    0
dtype: int64


In [7]:
df.dtypes

income     float64
age        float64
loan       float64
default      int64
dtype: object

In [15]:
import numpy as np
from scipy import stats
z = stats.zscore(df.astype(np.float64))
z = np.abs(z) 
f = (z < 3).all(axis=1)
df = df[f]



In [16]:
df

income        age          loan  default
0     66155.925100  59.017015   8106.532131        0
1     34415.153970  48.117153   6564.745018        0
2     57317.170060  63.108049   8020.953296        0
3     42709.534200  45.751972   6103.642260        0
4     66952.688850  18.584336   8770.099235        1
...            ...        ...           ...      ...
3423  60903.191726  21.933924  10367.081892        1
3424  62235.644695  25.033016   8083.900063        1
3425  25597.850590  26.350344   3810.110335        1
3426  48164.194974  23.141976   6529.652892        1
3427  33055.808635  26.289612   5351.851138        1

[3425 rows x 4 columns]

In [27]:
Y = df.loc[:,"default"]

In [28]:
X = df.iloc[:, 0:3]

In [29]:
Y

0       0
1       0
2       0
3       0
4       1
       ..
3423    1
3424    1
3425    1
3426    1
3427    1
Name: default, Length: 3425, dtype: int64

In [33]:
#logistic regression
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.3)
print(X_train, X_test, Y_train, Y_test )

from sklearn import linear_model
model = linear_model.LogisticRegression()
model.fit(X_train, Y_train)
pred = model.predict(X_train)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_train, pred)
print(cm)
accuracy = (cm[0,0]+cm[1,1])/sum(sum(cm))
print(accuracy)

pred = model.predict(X_test)
cm = confusion_matrix(Y_test, pred)
print(cm)
accuracy = (cm[0,0]+cm[1,1])/sum(sum(cm))
print(accuracy)


            income        age         loan
263   52757.794940  53.082214  2321.206314
198   38053.623130  26.206880  6110.572792
1143  26558.361060  57.833365    22.327933
882   69465.746960  20.585232  7983.705373
3342  25562.321031  23.355048  3096.272564
...            ...        ...          ...
919   56025.419730  29.396444  4341.626699
934   66217.944850  19.081624   745.076095
1072  52809.546290  61.013319  6276.830737
1651  32441.652010  58.709557   840.714207
3162  49790.144830  28.940075  7256.362154

[2397 rows x 3 columns]             income        age         loan
637   31091.276300  50.895543  4071.083034
1005  20491.564330  35.134837  1579.168249
2406  68706.428408  27.551071  9482.039920
1436  29237.256200  24.597574    23.916428
3035  36701.924055  28.029378  5653.120103
...            ...        ...          ...
60    32727.700730  34.474871  1087.919364
1232  68412.609850  28.155128   551.843081
309   51455.098450  37.285684  9447.117157
1450  28630.009510  27.291530

In [43]:
# decision tree
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.3)

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(max_depth=3)
model.fit(X_train,Y_train)
pred = model.predict(X_train)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_train, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/(sum(sum(cm)))
print(accuracy)

pred = model.predict(X_test)
cm = confusion_matrix(Y_test, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/(sum(sum(cm)))
print(accuracy)



[[1060  144]
 [   0 1193]]
0.9399249061326659
[[442  65]
 [  0 521]]
0.9367704280155642


In [46]:
from sklearn import tree
from sklearn import metrics

In [47]:
#optimisation for decision tree

X_train1, X_validate2, Y_train1, Y_validate2 = train_test_split(X_train, Y_train, test_size=0.2)


for i in range(100):
    print(i)
    model = tree.DecisionTreeRegressor(min_samples_split = i+2)
    model.fit(X_train1, Y_train1)
    pred = model.predict(X_validate2)
    rmse = metrics.mean_squared_error(Y_validate2, pred) ** 0.5
    print(rmse)

0
0.12909944487358055
1
0.11636866703140784
2
0.1070436048222094
3
0.1070436048222094
4
0.1070436048222094
5
0.10811944697793646
6
0.11735905652376448
7
0.10826987992118652
8
0.11749766053620592
9
0.10826987992118652
10
0.10826987992118652
11
0.10826987992118652
12
0.11749766053620592
13
0.12793494398070226
14
0.12793494398070226
15
0.11951575861789981
16
0.12793494398070226
17
0.12793494398070226
18
0.11139317509329619
19
0.12038177931356171
20
0.11139317509329619
21
0.11139317509329619
22
0.11139317509329619
23
0.11139317509329619
24
0.12038177931356171
25
0.12038177931356171
26
0.11983452829458685
27
0.11983452829458685
28
0.11983452829458685
29
0.11983452829458685
30
0.11983452829458685
31
0.11983452829458685
32
0.11983452829458685
33
0.11983452829458685
34
0.11983452829458685
35
0.11983452829458685
36
0.11983452829458685
37
0.11983452829458685
38
0.11983452829458685
39
0.11885617153401075
40
0.11885617153401075
41
0.11885617153401075
42
0.11885617153401075
43
0.11885617153401075
4

In [48]:
#random forest

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(max_depth=3)
model.fit(X_train, Y_train)
pred = model.predict(X_train)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_train, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))
print(accuracy)

pred = model.predict(X_test)
cm = confusion_matrix(Y_test, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))
print(accuracy)


[[1107  115]
 [   0 1175]]
0.952023362536504
[[436  53]
 [  3 536]]
0.9455252918287937


In [49]:
#XGBoost

from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier(max_depth=3)
model.fit(X_train, Y_train)
pred = model.predict(X_train)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_train, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))
print(accuracy)

pred = model.predict(X_test)
cm = confusion_matrix(Y_test, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))
print(accuracy)


[[1219    3]
 [   0 1175]]
0.9987484355444305
[[480   9]
 [  0 539]]
0.9912451361867705


In [50]:
#Neural network MLP

from sklearn.neural_network import MLPClassifier
model=MLPClassifier(solver="lbfgs",hidden_layer_sizes=(11,12))
model.fit(X,Y)
pred=model.predict(X)
print(pred)

#confusion matrix

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y,pred)
print(cm)

[1 1 1 ... 1 1 1]
[[   0 1711]
 [   0 1714]]


In [51]:
#dump model

import joblib
joblib.dump(model,"Creditcards")

['Creditcards']